# -*- coding: utf-8 -*-
import json

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        self.did_signin = False
        self.remember_me = False
        self.password_shown = False

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(350, 600)
        Form.setMinimumSize(QtCore.QSize(300, 600))
        Form.setMaximumSize(QtCore.QSize(350, 600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/stop-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background:rgb(254,254,254)")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.title_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Gilroy ExtraBold")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet("background:None;")
        self.title_lbl.setText("")
        self.title_lbl.setPixmap(QtGui.QPixmap("images/trackify large.png"))
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.sign_in_lbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sign_in_lbl.setFont(font)
        self.sign_in_lbl.setStyleSheet("color:rgb(101, 73, 154);\n"
                                       "background:None;")
        self.sign_in_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.sign_in_lbl.setObjectName("sign_in_lbl")
        self.verticalLayout.addWidget(self.sign_in_lbl)
        self.email_wgt = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_wgt.sizePolicy().hasHeightForWidth())
        self.email_wgt.setSizePolicy(sizePolicy)
        self.email_wgt.setMinimumSize(QtCore.QSize(300, 0))
        self.email_wgt.setMaximumSize(QtCore.QSize(300, 40))
        self.email_wgt.setStyleSheet("QWidget{\n"
                                     "    border: 1px solid rgb(179, 179, 179);\n"
                                     "    border-radius: 20px;\n"
                                     "}")
        self.email_wgt.setObjectName("email_wgt")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.email_wgt)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.email_lbl = QtWidgets.QLabel(self.email_wgt)
        self.email_lbl.setStyleSheet("border:None;")
        self.email_lbl.setText("")
        self.email_lbl.setPixmap(QtGui.QPixmap("images/email (2).png"))
        self.email_lbl.setObjectName("email_lbl")
        self.horizontalLayout.addWidget(self.email_lbl)
        self.email_line_edit = QtWidgets.QLineEdit(self.email_wgt)
        self.email_line_edit.setStyleSheet("border: None;")
        self.email_line_edit.setText("")
        self.email_line_edit.setObjectName("email_line_edit")
        self.horizontalLayout.addWidget(self.email_line_edit)
        self.verticalLayout.addWidget(self.email_wgt, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.password_wgt = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_wgt.sizePolicy().hasHeightForWidth())
        self.password_wgt.setSizePolicy(sizePolicy)
        self.password_wgt.setMinimumSize(QtCore.QSize(300, 40))
        self.password_wgt.setMaximumSize(QtCore.QSize(300, 40))
        self.password_wgt.setStyleSheet("QWidget{\n"
                                        "    border: 1px solid rgb(179, 179, 179);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.password_wgt.setObjectName("password_wgt")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.password_wgt)
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_lbl = QtWidgets.QLabel(self.password_wgt)
        self.password_lbl.setStyleSheet("border:None;")
        self.password_lbl.setText("")
        self.password_lbl.setPixmap(QtGui.QPixmap("images/padlock.png"))
        self.password_lbl.setObjectName("password_lbl")
        self.horizontalLayout_2.addWidget(self.password_lbl)
        self.password_line_edit = QtWidgets.QLineEdit(self.password_wgt)
        self.password_line_edit.setStyleSheet("border: None;")
        self.password_line_edit.setText("")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.horizontalLayout_2.addWidget(self.password_line_edit)
        self.show_password_lbl = QtWidgets.QLabel(self.password_wgt)
        self.show_password_lbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_password_lbl.setStyleSheet("border:None")
        self.show_password_lbl.setText("")
        self.show_password_lbl.setPixmap(QtGui.QPixmap("images/show.png"))
        self.show_password_lbl.setObjectName("show_password_lbl")
        self.horizontalLayout_2.addWidget(self.show_password_lbl)
        self.verticalLayout.addWidget(self.password_wgt, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.remember_me_chk_box = QtWidgets.QCheckBox(Form)
        self.remember_me_chk_box.setMinimumSize(QtCore.QSize(300, 0))
        self.remember_me_chk_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.remember_me_chk_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remember_me_chk_box.setStyleSheet("QCheckBox::indicator{\n"
                                               "    border: 1px solid rgb(101, 73, 154);\n"
                                               "    border-radius: 6px;\n"
                                               "}\n"
                                               "QCheckBox::indicator:checked\n"
                                               "{\n"
                                               "background-color : rgb(101, 73, 154);\n"
                                               "}\n"
                                               "QCheckBox{\n"
                                               "color: grey;\n"
                                               "}\n"
                                               "")
        self.remember_me_chk_box.setObjectName("remember_me_chk_box")
        self.verticalLayout.addWidget(self.remember_me_chk_box, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.signin_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signin_btn.sizePolicy().hasHeightForWidth())
        self.signin_btn.setSizePolicy(sizePolicy)
        self.signin_btn.setMinimumSize(QtCore.QSize(300, 30))
        self.signin_btn.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.signin_btn.setFont(font)
        self.signin_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signin_btn.setStyleSheet("QPushButton { \n"
                                      "    background:rgb(101, 73, 154); \n"
                                      "    color:white;\n"
                                      "    border: 2px solid rgb(101, 73, 154);\n"
                                      "    border-radius: 15px;\n"
                                      " }\n"
                                      "QPushButton:hover { \n"
                                      "    background:rgb(110, 80, 170);\n"
                                      "    border: 2px solid rgb(110, 80, 170);\n"
                                      "}\n"
                                      "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/user (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signin_btn.setIcon(icon1)
        self.signin_btn.setObjectName("signin_btn")
        self.verticalLayout.addWidget(self.signin_btn, 0, QtCore.Qt.AlignHCenter)
        self.error_lbl = QtWidgets.QLabel(Form)
        self.error_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.error_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Gilroy Light")
        self.error_lbl.setFont(font)
        self.error_lbl.setStyleSheet("color:red;\n"
                                     "background:None;")
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lbl.setObjectName("error_lbl")
        self.verticalLayout.addWidget(self.error_lbl)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self._connect_buttons(Form)

    def _connect_buttons(self, form):
        self.show_password_lbl.mousePressEvent = self.show_password
        self.signin_btn.clicked.connect(lambda: self.signin(form))

    def signin(self, form):
        if not len(self.email_line_edit.text()) == 0:
            if not len(self.password_line_edit.text()) == 0:
                with open('users.json', 'r') as data_base:
                    data = json.load(data_base)
                    error = 'Incorrect Email!'
                    for user in data:
                        user_name = user['credentials']['username']
                        password = user['credentials']['password']
                        if user_name == self.email_line_edit.text():
                            if password == self.password_line_edit.text():
                                if self.remember_me_chk_box.checkState() == 2:
                                    self.remember_me = True
                                with open('current_user.json', 'w') as user_file:
                                    user_file.writelines(json.dumps({
                                        'username': self.email_line_edit.text(),
                                        'password': self.password_line_edit.text()
                                    }))
                                error = ''
                                self.did_signin = True
                                form.close()
                            else:
                                error = 'Incorrect Password!'
                                break
                    data_base.close()
                    user_file.close()
                    self.error_lbl.setText(error)
            else:
                self.error_lbl.setText('Password Field Is Empty!')
        else:
            self.error_lbl.setText('Email Field Is Empty!')

    def show_password(self, event):
        self.password_shown = not self.password_shown
        if self.password_shown:
            self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
            self.show_password_lbl.setPixmap(QtGui.QPixmap("images/hide.png"))
        else:
            self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
            self.show_password_lbl.setPixmap(QtGui.QPixmap("images/show.png"))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.sign_in_lbl.setText(_translate("Form", "Sign In Now"))
        self.email_line_edit.setPlaceholderText(_translate("Form", "Email"))
        self.password_line_edit.setPlaceholderText(_translate("Form", "Password"))
        self.remember_me_chk_box.setText(_translate("Form", "Remember Me"))
        self.signin_btn.setText(_translate("Form", "SIGN IN"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
