# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_name_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def __init__(self, parent):
        super().__init__(parent=parent)
        self.setupUi(self)
        self.project_name = ''

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 228)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/stop-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:rgb(254,254,254);\n"
                             "border:1px solid white;\n"
                             "border-radius:20px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_lbl.sizePolicy().hasHeightForWidth())
        self.title_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gilroy ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet("background:rgb(254,254,254);padding:10px")
        self.title_lbl.setText("")
        self.title_lbl.setPixmap(QtGui.QPixmap("images/tarckify-small.png"))
        self.title_lbl.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.bottom_wgt = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_wgt.sizePolicy().hasHeightForWidth())
        self.bottom_wgt.setSizePolicy(sizePolicy)
        self.bottom_wgt.setObjectName("bottom_wgt")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom_wgt)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.project_name_lbl = QtWidgets.QLabel(self.bottom_wgt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_name_lbl.sizePolicy().hasHeightForWidth())
        self.project_name_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.project_name_lbl.setFont(font)
        self.project_name_lbl.setStyleSheet("color:rgb(101, 73, 154)")
        self.project_name_lbl.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.project_name_lbl.setObjectName("project_name_lbl")
        self.verticalLayout_2.addWidget(self.project_name_lbl)
        self.project_name_line_wgt = QtWidgets.QWidget(self.bottom_wgt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_name_line_wgt.sizePolicy().hasHeightForWidth())
        self.project_name_line_wgt.setSizePolicy(sizePolicy)
        self.project_name_line_wgt.setMinimumSize(QtCore.QSize(300, 41))
        self.project_name_line_wgt.setMaximumSize(QtCore.QSize(300, 41))
        self.project_name_line_wgt.setStyleSheet("QWidget{\n"
                                                 "    border: 1px solid black;\n"
                                                 "    border-radius: 20px;\n"
                                                 "}")
        self.project_name_line_wgt.setObjectName("project_name_line_wgt")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.project_name_line_wgt)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_name_line_lbl = QtWidgets.QLabel(self.project_name_line_wgt)
        self.project_name_line_lbl.setStyleSheet("border:None;")
        self.project_name_line_lbl.setText("")
        self.project_name_line_lbl.setPixmap(QtGui.QPixmap("images/project-management.png"))
        self.project_name_line_lbl.setObjectName("project_name_line_lbl")
        self.horizontalLayout.addWidget(self.project_name_line_lbl)
        self.project_name_line_edit = QtWidgets.QLineEdit(self.project_name_line_wgt)
        self.project_name_line_edit.setStyleSheet("border: None;")
        self.project_name_line_edit.setText("")
        self.project_name_line_edit.setObjectName("project_name_line_edit")
        self.horizontalLayout.addWidget(self.project_name_line_edit)
        self.verticalLayout_2.addWidget(self.project_name_line_wgt, 0, QtCore.Qt.AlignHCenter)
        self.error_value_lbl = QtWidgets.QLabel(self.bottom_wgt)
        self.error_value_lbl.setText("")
        self.error_value_lbl.setObjectName("error_value_lbl")
        self.error_value_lbl.setStyleSheet("color:red;")
        self.verticalLayout_2.addWidget(self.error_value_lbl)
        self.accept_btn = QtWidgets.QPushButton(self.bottom_wgt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept_btn.sizePolicy().hasHeightForWidth())
        self.accept_btn.setSizePolicy(sizePolicy)
        self.accept_btn.setMinimumSize(QtCore.QSize(100, 31))
        self.accept_btn.setMaximumSize(QtCore.QSize(100, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.accept_btn.setFont(font)
        self.accept_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accept_btn.setStyleSheet("QPushButton { \n"
                                      "    background:rgb(101, 73, 154); \n"
                                      "    color:white;\n"
                                      "    border: 2px solid rgb(101, 73, 154);\n"
                                      "    border-radius: 15px;\n"
                                      " }\n"
                                      "QPushButton:hover { \n"
                                      "    background:rgb(110, 80, 170);\n"
                                      "    border: 2px solid rgb(110, 80, 170);\n"
                                      "}\n"
                                      "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accept_btn.setIcon(icon1)
        self.accept_btn.setObjectName("accept_btn")
        self.verticalLayout_2.addWidget(self.accept_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.bottom_wgt)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.setup_buttons()

    def setup_buttons(self):
        self.accept_btn.clicked.connect(self.return_values)

    def return_values(self):
        self.project_name = self.project_name_line_edit.text()
        if not len(str(self.project_name)) == 0:
            self.accept()
        else:
            self.error_value_lbl.setText('Error : Project Not specified')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Trackify"))
        self.project_name_lbl.setText(_translate("Dialog", "Project Name"))
        self.project_name_line_edit.setPlaceholderText(_translate("Dialog", "Project Name"))
        self.accept_btn.setText(_translate("Dialog", "OK"))
